config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :jobs, only: [:index]

  root "jobs#index"

  get "app_inspector", to: "app_inspector#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OSC Reporting</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="action-cable-url" content="/pun/<%= Rails.env.development? ? 'dev' : 'sys' %>/osc-reporting/cable">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <header>

    <nav class="navbar navbar-expand-lg navbar-blue navbar-static-top" id="main-nav">
      <div class="container-fluid">
        <div class="navbar-header">
          <%# #FIXME: ood_appkit can supply these links but doesn't have a rails 7 compatible version yet! %>
          <%= link_to 'OSC OnDemand', 'ondemand.osc.edu/pun/dev/dashboard', class: "navbar-brand" %>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav navbar-right">
            <li class="nav-item">
              <%= link_to "Jobs", jobs_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "App Inspector", app_inspector_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <a href="https://github.com/OSC/frame-renderer/blob/master/README.md" class="nav-link">Help</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

  </header>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>